/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ai.ondevice.app.ui.common.tos

import android.content.Intent
import android.net.Uri
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.expandVertically
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.animation.shrinkVertically
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ExpandMore
import androidx.compose.material.icons.outlined.Lock
import androidx.compose.material.icons.outlined.PhoneAndroid
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.rotate
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.delay

data class TosSection(
    val title: String,
    val content: String,
    val isExpanded: Boolean = false
)

@Composable
fun PremiumTosDialog(
    onDismiss: () -> Unit,
    onAccept: () -> Unit
) {
    val context = LocalContext.current
    val listState = rememberLazyListState()

    // Track scroll progress
    var hasScrolledToBottom by remember { mutableStateOf(false) }
    var scrollProgress by remember { mutableStateOf(0f) }

    // TOS sections with accordion state
    var sections by remember {
        mutableStateOf(
            listOf(
                TosSection(
                    title = "Service Agreement",
                    content = "OnDevice AI is built on open-source technology (Apache 2.0). Your purchase supports professional packaging, testing, updates, and customer support.\n\nBy using this app, you accept responsibility for content generated by the AI models. All processing happens entirely on your device."
                ),
                TosSection(
                    title = "AI Model Terms",
                    content = "Some AI models have specific usage terms:\n\n" +
                        "• Gemma models: Subject to Google's Gemma Terms of Use and Prohibited Use Policy\n" +
                        "• Other models: Subject to their respective licenses\n\n" +
                        "By using these models, you agree to their terms."
                ),
                TosSection(
                    title = "Privacy & Data",
                    content = "All AI inference runs entirely on your device. No data is sent to external servers during normal operation.\n\n" +
                        "Optional features like model downloads from HuggingFace require internet access, but your conversations and personal data remain on-device."
                ),
                TosSection(
                    title = "Limitations",
                    content = "AI models may produce inaccurate or inappropriate content. Use with discretion and verify critical information.\n\n" +
                        "Model performance depends on your device's hardware capabilities. We recommend devices with 6GB+ RAM for best results."
                )
            )
        )
    }

    // Monitor scroll progress
    LaunchedEffect(listState.canScrollForward) {
        while (true) {
            val layoutInfo = listState.layoutInfo
            val viewportHeight = layoutInfo.viewportEndOffset - layoutInfo.viewportStartOffset
            val totalItemsHeight = layoutInfo.totalItemsCount * 100 // Approximate

            if (totalItemsHeight > 0) {
                val scrollOffset = listState.firstVisibleItemIndex * 100 + listState.firstVisibleItemScrollOffset
                scrollProgress = (scrollOffset.toFloat() / (totalItemsHeight - viewportHeight)).coerceIn(0f, 1f)
            }

            hasScrolledToBottom = !listState.canScrollForward
            delay(100)
        }
    }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            Column {
                Text(
                    "OnDevice AI - Terms of Service",
                    style = MaterialTheme.typography.headlineSmall
                )

                // Scroll progress indicator
                if (!hasScrolledToBottom) {
                    Spacer(modifier = Modifier.height(8.dp))
                    LinearProgressIndicator(
                        progress = { scrollProgress },
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(3.dp),
                        color = MaterialTheme.colorScheme.primary,
                    )
                }
            }
        },
        text = {
            LazyColumn(
                modifier = Modifier
                    .fillMaxWidth()
                    .heightIn(max = 500.dp),
                state = listState,
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                // Privacy Highlights Section
                item(key = "privacy_highlights") {
                    Card(
                        colors = CardDefaults.cardColors(
                            containerColor = MaterialTheme.colorScheme.primaryContainer
                        ),
                        shape = RoundedCornerShape(12.dp)
                    ) {
                        Column(
                            modifier = Modifier.padding(16.dp),
                            verticalArrangement = Arrangement.spacedBy(12.dp)
                        ) {
                            Text(
                                "Privacy Highlights",
                                style = MaterialTheme.typography.titleMedium,
                                fontWeight = FontWeight.Bold,
                                color = MaterialTheme.colorScheme.onPrimaryContainer
                            )

                            PrivacyHighlightItem(
                                icon = Icons.Outlined.Lock,
                                text = "All processing on-device - your data never leaves your phone"
                            )
                            PrivacyHighlightItem(
                                icon = Icons.Outlined.PhoneAndroid,
                                text = "Works offline - no internet required for AI conversations"
                            )
                            PrivacyHighlightItem(
                                icon = Icons.Outlined.Lock,
                                text = "You own your data - export or delete anytime"
                            )
                        }
                    }
                }

                // Privacy Trust Badges
                item(key = "trust_badges") {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceEvenly
                    ) {
                        TrustBadge(
                            icon = "🔒",
                            text = "All processing\non-device"
                        )
                        TrustBadge(
                            icon = "📱",
                            text = "No data leaves\nyour phone"
                        )
                    }
                }

                // Accordion Sections
                sections.forEachIndexed { index, section ->
                    item(key = "section_$index") {
                        TosAccordionSection(
                            section = section,
                            onToggle = {
                                sections = sections.toMutableList().also {
                                    it[index] = section.copy(isExpanded = !section.isExpanded)
                                }
                            }
                        )
                    }
                }

                // External Links
                item(key = "external_links") {
                    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                        OutlinedButton(
                            onClick = {
                                val intent = Intent(Intent.ACTION_VIEW, Uri.parse("https://ondevice.ai/legal/terms.html"))
                                context.startActivity(intent)
                            },
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Text("View Full Terms of Service")
                        }

                        OutlinedButton(
                            onClick = {
                                val intent = Intent(Intent.ACTION_VIEW, Uri.parse("https://ondevice.ai/legal/privacy.html"))
                                context.startActivity(intent)
                            },
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Text("View Privacy Policy")
                        }

                        OutlinedButton(
                            onClick = {
                                val intent = Intent(Intent.ACTION_VIEW, Uri.parse("https://ai.google.dev/gemma/terms"))
                                context.startActivity(intent)
                            },
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Text("View Gemma Terms of Use")
                        }
                    }
                }

                // Scroll hint
                if (!hasScrolledToBottom) {
                    item(key = "scroll_hint") {
                        Text(
                            "↓ Please scroll to the bottom to continue",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.primary,
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(vertical = 8.dp)
                        )
                    }
                }
            }
        },
        confirmButton = {
            Button(
                onClick = onAccept,
                enabled = hasScrolledToBottom,
                modifier = Modifier.fillMaxWidth(0.48f)
            ) {
                Text("Accept and Continue")
            }
        },
        dismissButton = {
            OutlinedButton(
                onClick = onDismiss,
                modifier = Modifier.fillMaxWidth(0.48f)
            ) {
                Text("Decline")
            }
        }
    )
}

@Composable
private fun PrivacyHighlightItem(
    icon: ImageVector,
    text: String
) {
    Row(
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Icon(
            imageVector = icon,
            contentDescription = null,
            tint = MaterialTheme.colorScheme.primary,
            modifier = Modifier.size(24.dp)
        )
        Text(
            text = text,
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onPrimaryContainer
        )
    }
}

@Composable
private fun TrustBadge(
    icon: String,
    text: String
) {
    Surface(
        shape = RoundedCornerShape(8.dp),
        color = MaterialTheme.colorScheme.surface,
        tonalElevation = 2.dp,
        modifier = Modifier.width(140.dp)
    ) {
        Column(
            modifier = Modifier.padding(12.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.spacedBy(4.dp)
        ) {
            Text(
                text = icon,
                style = MaterialTheme.typography.headlineMedium
            )
            Text(
                text = text,
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }
    }
}

@Composable
private fun TosAccordionSection(
    section: TosSection,
    onToggle: () -> Unit
) {
    Card(
        onClick = onToggle,
        shape = RoundedCornerShape(8.dp)
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp)
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    text = section.title,
                    style = MaterialTheme.typography.titleSmall,
                    fontWeight = FontWeight.SemiBold
                )

                val rotation by animateFloatAsState(
                    targetValue = if (section.isExpanded) 180f else 0f,
                    label = "expand_icon_rotation"
                )

                Icon(
                    imageVector = Icons.Default.ExpandMore,
                    contentDescription = if (section.isExpanded) "Collapse" else "Expand",
                    modifier = Modifier.rotate(rotation)
                )
            }

            AnimatedVisibility(
                visible = section.isExpanded,
                enter = expandVertically() + fadeIn(),
                exit = shrinkVertically() + fadeOut()
            ) {
                Text(
                    text = section.content,
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    modifier = Modifier.padding(top = 12.dp)
                )
            }
        }
    }
}
